CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    surname TEXT DEFAULT NULL,
    phone TEXT(12) DEFAULT NULL,
    email TEXT(100) DEFAULT NULL,
    information TEXT DEFAULT NULL
);
